-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-7",
    mode     = "3840x2160",
    position = "1920x0",
    scale    = 1,
})
