-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- MONITORS

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080",
    position = "1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-6",
    mode     = "1920x1080",
    position = "1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-4",
    mode     = "1920x1080",
    position = "3840x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-8",
    mode     = "1920x1080",
    position = "1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-5",
    mode     = "1920x1080",
    position = "3840x0",
    scale    = 1,
})

-- VINCENT SETUP

-- monitor=DP-6, 1920x1080, 0x0, 1

-- monitor=DP-4, 1920x1080, 0x0, 1

-- monitor=DP-8, 1920x1080, 1920x0, 1

-- monitor=DP-5, 1920x1080, 1920x0, 1

-- monitor=eDP-1, 1920x1200, 3840x0, 1

--

--WORKSPACES

hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-4",
    default = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-6",
    default = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-6",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-6",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-6",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-6",
})

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-8",
    default = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-5",
    default = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-5",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-5",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-5",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-5",
})
